[options]
admin_passwd = changepassword
xmlrpc_port = 8069
xmlrpc_interface = 0.0.0.0
dbfilter = .*
db_user = odoo
db_password = postgres
db_port = 5432
longpolling_port = 8072
proxy_mode = True
db_host = db
addons_path=/mnt/extra-addons/citas,/mnt/extra-addons/muk_base,/mnt/extra-addons/muk_web,/mnt/extra-addons/partner-contact,/mnt/extra-addons/vertical-medical
